store-before/config/routes.rb
Store::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :products
  root to: 'products#index'
end

store-before/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :released_at
end

store-before/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_format_of :name, with: /^\w+$/
end

store-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

store-before/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order("name #{params[:direction]}")
  end

  def show
    @product = Product.find(params[:id])
  end
end

store-before/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:return_to] = params[:return_to] if params[:return_to]
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_url = session.delete(:return_to) || root_url
      redirect_to redirect_url
    else
      flash.now.alert = "Name or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

store-before/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

store-before/app/helpers/application_helper.rb
module ApplicationHelper
end

store-before/app/helpers/products_helper.rb
module ProductsHelper
end

store-before/app/helpers/sessions_helper.rb
module SessionsHelper
end

store-before/app/helpers/users_helper.rb
module UsersHelper
end

store-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if current_user %>
          Logged in as <%= current_user.name %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

store-before/app/views/products/index.html.erb
<h1>Products</h1>

<p><%= link_to "Reverse sort order", direction: (params[:direction] == "desc" ? "asc" : "desc") %></p>

<table id="products">
  <tr>
    <th>Product Name</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product.name) %></td>
    <td><%= product.released_at.strftime("%B %e, %Y") %></td>
    <td><%= number_to_currency(product.price) %></td>
  </tr>
<% end %>
</table>

store-before/app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Release Date:</b>
  <%= @product.released_at.strftime("%B %e, %Y") %>
</p>

<%= link_to 'Destroy', @product, method: :delete, confirm: "Are you sure?" %> |
<%= link_to 'List Products', products_path %>

store-before/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>